jobs:
  build:
    runs-on: macos-latest
    name: Build Jnilib on macOS
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: |
          java -version
          ant -version
          ant -f plugins/OSX/build.xml 
      