name: Build Jnilib on macOS

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: |
          java -version
          ant -version
          ls /Library/Java/JavaVirtualMachines/
          echo $JAVA_HOME
          ant -f plugins/OSX/build.xml 
      