name: Java macOS CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on:  macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn --batch-mode install --file pom.xml --projects applet,coreAPI,plugins/OSX

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-natives
          path: plugins/OSX/target/*.jar
